apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp                    # Matches pods with label "app: myapp"
  replicas: 5                        # Creates two replicas of the myapp pod
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80       # Exposes port 8080 within the container
