apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp                  # Matches pods with the label "app: myapp"
  ports:
    - port: 80                # Service port (external)
      protocol: TCP
      targetPort: 80          # Port on the pod that the application listens on
  type: ClusterIP               # Default service type (internal-only)
